services:
  kyvc-frontend-dev:
    image: nginx:alpine
    container_name: kyvc-frontend-dev
    restart: unless-stopped
    ports:
      - "3001:80"
    volumes:
      - /opt/kyvc/logs/dev/frontend:/var/log/nginx
    networks:
      - kyvc-public

  kyvc-backend-dev:
    image: ghcr.io/de-butler-kyvc/kyvc-backend:dev
    container_name: kyvc-backend-dev
    restart: unless-stopped
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: kyvc-postgres
      DB_PORT: 5432
      DB_NAME: kyvc_dev
      DB_USER: kyvc_admin
      DB_PASSWORD: change_me
      APP_STORAGE_PATH: /app/storage
      LOG_PATH: /app/logs
      CORE_BASE_URL: http://kyvc-core-dev:8090
    volumes:
      - /mnt/kyvc-dev:/app/storage
      - /opt/kyvc/logs/dev/backend:/app/logs
    networks:
      - kyvc-public
      - kyvc-internal
      - kyvc-db

  kyvc-core-dev:
    image: ghcr.io/de-butler-kyvc/kyvc-core:dev
    container_name: kyvc-core-dev
    restart: unless-stopped
    expose:
      - "8090"
    environment:
      ENV: dev
      LOG_PATH: /app/logs
    volumes:
      - /opt/kyvc/logs/dev/core:/app/logs
    networks:
      - kyvc-internal
      - kyvc-db

  kyvc-admin-frontend-dev:
    image: nginx:alpine
    container_name: kyvc-admin-frontend-dev
    restart: unless-stopped
    ports:
      - "3003:80"
    volumes:
      - /opt/kyvc/logs/dev/admin-frontend:/var/log/nginx
    networks:
      - kyvc-public
      - kyvc-admin-internal

  kyvc-back-admin-dev:
    image: ghcr.io/de-butler-kyvc/kyvc-backend-admin:dev
    container_name: kyvc-back-admin-dev
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: kyvc-postgres
      DB_PORT: 5432
      DB_NAME: kyvc_dev
      DB_USER: kyvc_admin
      DB_PASSWORD: change_me
      LOG_PATH: /app/logs
      SERVICE_LOG_PATH: /app/service-logs
      CORE_ADMIN_BASE_URL: http://kyvc-core-admin-dev:8091
    volumes:
      - /opt/kyvc/logs/dev/back-admin:/app/logs
      - /opt/kyvc/logs/dev:/app/service-logs:ro
    networks:
      - kyvc-admin-internal
      - kyvc-db

  kyvc-core-admin-dev:
    image: ghcr.io/de-butler-kyvc/kyvc-core-admin:dev
    container_name: kyvc-core-admin-dev
    restart: unless-stopped
    expose:
      - "8091"
    environment:
      ENV: dev
      LOG_PATH: /app/logs
      SERVICE_LOG_PATH: /app/service-logs
    volumes:
      - /opt/kyvc/logs/dev/core-admin:/app/logs
    networks:
      - kyvc-admin-internal
      - kyvc-db

networks:
  kyvc-public:
    external: true
  kyvc-internal:
    external: true
  kyvc-admin-internal:
    external: true
  kyvc-db:
    external: true
