services:
  kyvc-frontend-dev:
    image: nginx:alpine
    container_name: kyvc-frontend-dev
    restart: unless-stopped
    ports:
      - "3001:80"
    volumes:
      - /opt/kyvc/logs/dev/frontend:/var/log/nginx
    networks:
      - kyvc-public

  kyvc-backend-dev:
    image: ghcr.io/de-butler-kyvc/kyvc-backend:dev
    container_name: kyvc-backend-dev
    restart: unless-stopped
    env_file:
      - .env.common
      - .env.backend
    ports:
      - "8082:8080"
    volumes:
      - /mnt/kyvc-dev:/app/storage
      - /opt/kyvc/logs/dev/backend:/app/logs
    networks:
      - kyvc-public
      - kyvc-internal
      - kyvc-dev-net

  kyvc-core-dev:
    image: ghcr.io/de-butler-kyvc/kyvc-core:dev
    container_name: kyvc-core-dev
    restart: unless-stopped
    env_file:
      - .env.common
      - .env.core
    ports:
      - "8092:8090"
    volumes:
      - /opt/kyvc/logs/dev/core:/app/logs
      - /opt/kyvc/secrets/dev/core/issuer-key.pem:/run/secrets/issuer-key.pem:ro
    networks:
      - kyvc-internal
      - kyvc-dev-net

  kyvc-admin-frontend-dev:
    image: nginx:alpine
    container_name: kyvc-admin-frontend-dev
    restart: unless-stopped
    ports:
      - "3003:80"
    volumes:
      - /opt/kyvc/logs/dev/admin-frontend:/var/log/nginx
    networks:
      - kyvc-public
      - kyvc-admin-internal

  kyvc-back-admin-dev:
    image: ghcr.io/de-butler-kyvc/kyvc-backend-admin:dev
    container_name: kyvc-back-admin-dev
    restart: unless-stopped
    env_file:
      - .env.common
      - .env.backend_admin
    ports:
      - "8083:8080"
    volumes:
      - /opt/kyvc/logs/dev/back-admin:/app/logs
      - /opt/kyvc/logs/dev:/app/service-logs:ro
    networks:
      - kyvc-admin-internal
      - kyvc-dev-net

  kyvc-core-admin-dev:
    image: ghcr.io/de-butler-kyvc/kyvc-core-admin:dev
    container_name: kyvc-core-admin-dev
    restart: unless-stopped
    env_file:
      - .env.common
      - .env.core_admin
    ports:
      - "8093:8091"
    volumes:
      - /opt/kyvc/logs/dev/core-admin:/app/logs
    networks:
      - kyvc-admin-internal
      - kyvc-dev-net

networks:
  kyvc-public:
    external: true
  kyvc-internal:
    external: true
  kyvc-admin-internal:
    external: true
  kyvc-dev-net:
    external: true
