services:
  kyvc-postgres-back-dev:
    image: postgres:16
    container_name: kyvc-postgres-back-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: kyvc_back
      POSTGRES_USER: ${POSTGRES_BACK_DEV_USER}
      POSTGRES_PASSWORD: ${POSTGRES_BACK_DEV_PASSWORD}
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - /opt/kyvc/postgres/back-dev/data:/var/lib/postgresql/data
    networks:
      - kyvc-dev-net

  kyvc-postgres-back-prod:
    image: postgres:16
    container_name: kyvc-postgres-back-prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: kyvc_back
      POSTGRES_USER: ${POSTGRES_BACK_PROD_USER}
      POSTGRES_PASSWORD: ${POSTGRES_BACK_PROD_PASSWORD}
    ports:
      - "127.0.0.1:5434:5432"
    volumes:
      - /opt/kyvc/postgres/back-prod/data:/var/lib/postgresql/data
    networks:
      - kyvc-prod-net

networks:
  kyvc-dev-net:
    external: true
  kyvc-prod-net:
    external: true
