from enum import StrEnum


class LegalEntityType(StrEnum):
    STOCK_COMPANY = "STOCK_COMPANY"
    LIMITED_COMPANY = "LIMITED_COMPANY"
    LIMITED_PARTNERSHIP = "LIMITED_PARTNERSHIP"
    GENERAL_PARTNERSHIP = "GENERAL_PARTNERSHIP"
    INCORPORATED_ASSOCIATION = "INCORPORATED_ASSOCIATION"
    FOUNDATION = "FOUNDATION"
    COOPERATIVE = "COOPERATIVE"
    UNIQUE_NUMBER_ORGANIZATION = "UNIQUE_NUMBER_ORGANIZATION"
    FOREIGN_COMPANY = "FOREIGN_COMPANY"


class ApplicantRole(StrEnum):
    REPRESENTATIVE = "REPRESENTATIVE"
    DELEGATE = "DELEGATE"


class DocumentType(StrEnum):
    BUSINESS_REGISTRATION = "BUSINESS_REGISTRATION"
    CORPORATE_REGISTRY = "CORPORATE_REGISTRY"
    SHAREHOLDER_REGISTRY = "SHAREHOLDER_REGISTRY"
    STOCK_CHANGE_STATEMENT = "STOCK_CHANGE_STATEMENT"
    INVESTOR_REGISTRY = "INVESTOR_REGISTRY"
    MEMBER_REGISTRY = "MEMBER_REGISTRY"
    BOARD_REGISTRY = "BOARD_REGISTRY"
    ARTICLES_OF_ASSOCIATION = "ARTICLES_OF_ASSOCIATION"
    OPERATING_RULES = "OPERATING_RULES"
    REGULATIONS = "REGULATIONS"
    MEETING_MINUTES = "MEETING_MINUTES"
    OFFICIAL_LETTER = "OFFICIAL_LETTER"
    PURPOSE_PROOF_DOCUMENT = "PURPOSE_PROOF_DOCUMENT"
    ORGANIZATION_IDENTITY_CERTIFICATE = "ORGANIZATION_IDENTITY_CERTIFICATE"
    INVESTMENT_REGISTRATION_CERTIFICATE = "INVESTMENT_REGISTRATION_CERTIFICATE"
    BENEFICIAL_OWNER_PROOF_DOCUMENT = "BENEFICIAL_OWNER_PROOF_DOCUMENT"
    POWER_OF_ATTORNEY = "POWER_OF_ATTORNEY"
    SEAL_CERTIFICATE = "SEAL_CERTIFICATE"
    UNKNOWN = "UNKNOWN"


class AssessmentStatus(StrEnum):
    NORMAL = "NORMAL"
    SUPPLEMENT_REQUIRED = "SUPPLEMENT_REQUIRED"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
    REJECTED = "REJECTED"


class CheckStatus(StrEnum):
    PASS = "PASS"
    WARN = "WARN"
    FAIL = "FAIL"
    UNKNOWN = "UNKNOWN"


class Severity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class HolderType(StrEnum):
    INDIVIDUAL = "INDIVIDUAL"
    CORPORATE = "CORPORATE"
    UNKNOWN = "UNKNOWN"


class BeneficialOwnershipStatus(StrEnum):
    RESOLVED = "RESOLVED"
    NEEDS_SUPPLEMENT = "NEEDS_SUPPLEMENT"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
    UNRESOLVED = "UNRESOLVED"


class BeneficialOwnershipMethod(StrEnum):
    OWNERSHIP_THRESHOLD = "OWNERSHIP_THRESHOLD"
    LARGEST_SHAREHOLDER = "LARGEST_SHAREHOLDER"
    REPRESENTATIVE_FALLBACK = "REPRESENTATIVE_FALLBACK"
    CORPORATE_SHAREHOLDER_RECURSIVE_CHECK_REQUIRED = "CORPORATE_SHAREHOLDER_RECURSIVE_CHECK_REQUIRED"


class DelegationResult(StrEnum):
    AUTHORIZED = "AUTHORIZED"
    PARTIALLY_AUTHORIZED = "PARTIALLY_AUTHORIZED"
    NOT_AUTHORIZED = "NOT_AUTHORIZED"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
