services:
  kyvc-frontend-prod:
    image: nginx:alpine
    container_name: kyvc-frontend-prod
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - /opt/kyvc/logs/prod/frontend:/var/log/nginx
    networks:
      - kyvc-public

  kyvc-backend-prod:
    image: ghcr.io/de-butler-kyvc/kyvc-backend:prod
    container_name: kyvc-backend-prod
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: kyvc-postgres
      DB_PORT: 5432
      DB_NAME: kyvc_prod
      DB_USER: kyvc_admin
      DB_PASSWORD: change_me
      APP_STORAGE_PATH: /app/storage
      LOG_PATH: /app/logs
      CORE_BASE_URL: http://kyvc-core-prod:8090
    volumes:
      - /mnt/kyvc-prod:/app/storage
      - /opt/kyvc/logs/prod/backend:/app/logs
    networks:
      - kyvc-public
      - kyvc-internal
      - kyvc-db

  kyvc-core-prod:
    image: ghcr.io/de-butler-kyvc/kyvc-core:prod
    container_name: kyvc-core-prod
    restart: unless-stopped
    expose:
      - "8090"
    environment:
      ENV: prod
      LOG_PATH: /app/logs
    volumes:
      - /opt/kyvc/logs/prod/core:/app/logs
    networks:
      - kyvc-internal
      - kyvc-db

  kyvc-admin-frontend-prod:
    image: nginx:alpine
    container_name: kyvc-admin-frontend-prod
    restart: unless-stopped
    ports:
      - "3002:80"
    volumes:
      - /opt/kyvc/logs/prod/admin-frontend:/var/log/nginx
    networks:
      - kyvc-public
      - kyvc-admin-internal

  kyvc-back-admin-prod:
    image: ghcr.io/de-butler-kyvc/kyvc-backend-admin:prod
    container_name: kyvc-back-admin-prod
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: kyvc-postgres
      DB_PORT: 5432
      DB_NAME: kyvc_prod
      DB_USER: kyvc_admin
      DB_PASSWORD: change_me
      LOG_PATH: /app/logs
      SERVICE_LOG_PATH: /app/service-logs
      CORE_ADMIN_BASE_URL: http://kyvc-core-admin-prod:8091
    volumes:
      - /opt/kyvc/logs/prod/back-admin:/app/logs
      - /opt/kyvc/logs/prod:/app/service-logs:ro
    networks:
      - kyvc-admin-internal
      - kyvc-db

  kyvc-core-admin-prod:
    image: ghcr.io/de-butler-kyvc/kyvc-core-admin:prod
    container_name: kyvc-core-admin-prod
    restart: unless-stopped
    expose:
      - "8091"
    environment:
      ENV: prod
      LOG_PATH: /app/logs
      SERVICE_LOG_PATH: /app/service-logs
    volumes:
      - /opt/kyvc/logs/prod/core-admin:/app/logs
    networks:
      - kyvc-admin-internal
      - kyvc-db

networks:
  kyvc-public:
    external: true
  kyvc-internal:
    external: true
  kyvc-admin-internal:
    external: true
  kyvc-db:
    external: true
