services:
  kyvc-frontend-prod:
    image: ghcr.io/de-butler-kyvc/kyvc-frontend:prod
    build:
      context: ../../../
      dockerfile: infra/docker/frontend/Dockerfile
      args:
        NGINX_CONF: prod.conf
        KYVC_ENV: prod
    container_name: kyvc-frontend-prod
    restart: unless-stopped
    environment:
      TZ: Asia/Seoul
    ports:
      - "3000:80"
    volumes:
      - /opt/kyvc/logs/prod/frontend:/var/log/nginx
    networks:
      - kyvc-public
      - kyvc-admin-internal

  kyvc-backend-prod:
    image: ghcr.io/de-butler-kyvc/kyvc-backend:prod
    container_name: kyvc-backend-prod
    restart: unless-stopped
    env_file:
      - .env.common
      - .env.backend
    environment:
      TZ: Asia/Seoul
    ports:
      - "8080:8080"
    volumes:
      - /mnt/kyvc-prod:/app/storage
      - /opt/kyvc/logs/prod/backend:/app/logs
    networks:
      - kyvc-public
      - kyvc-internal
      - kyvc-prod-net

  kyvc-core-prod:
    image: ghcr.io/de-butler-kyvc/kyvc-core:prod
    container_name: kyvc-core-prod
    restart: unless-stopped
    env_file:
      - .env.common
      - .env.core
    environment:
      TZ: Asia/Seoul
    ports:
      - "8090:8090"
    volumes:
      - /opt/kyvc/logs/prod/core:/app/logs
      - /opt/kyvc/secrets/prod/core/issuer-key.pem:/run/secrets/issuer-key.pem:ro
    networks:
      - kyvc-internal
      - kyvc-prod-net

  kyvc-back-admin-prod:
    image: ghcr.io/de-butler-kyvc/kyvc-backend-admin:prod
    container_name: kyvc-back-admin-prod
    restart: unless-stopped
    env_file:
      - .env.common
      - .env.backend_admin
    environment:
      TZ: Asia/Seoul
    ports:
      - "8081:8080"
    volumes:
      - /opt/kyvc/logs/prod/back-admin:/app/logs
      - /opt/kyvc/logs/prod:/app/service-logs:ro
    networks:
      - kyvc-admin-internal
      - kyvc-prod-net

  kyvc-core-admin-prod:
    image: ghcr.io/de-butler-kyvc/kyvc-core-admin:prod
    container_name: kyvc-core-admin-prod
    restart: unless-stopped
    env_file:
      - .env.common
      - .env.core_admin
    environment:
      TZ: Asia/Seoul
    ports:
      - "8091:8091"
    volumes:
      - /opt/kyvc/logs/prod/core-admin:/app/logs
    networks:
      - kyvc-admin-internal
      - kyvc-prod-net

networks:
  kyvc-public:
    external: true
  kyvc-internal:
    external: true
  kyvc-admin-internal:
    external: true
  kyvc-prod-net:
    external: true
