spring:
  config:
    activate:
      on-profile: prod
  flyway:
    enabled: ${FLYWAY_ENABLED:false}
  jpa:
    properties:
      hibernate:
        format_sql: false

server:
  forward-headers-strategy: framework

logging:
  level:
    root: INFO
    com.kyvc.backendadmin: INFO
