server {
    listen 80;
    server_name dev-kyvc.khuoo.synology.me;

    root /usr/share/nginx/html/frontend;
    index index.html;

    access_log /var/log/nginx/frontend.access.log;
    error_log /var/log/nginx/error.log;
    absolute_redirect off;
    resolver 127.0.0.11 ipv6=off;
    set $backend_api http://kyvc-backend-dev:8080;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass $backend_api/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
    }
}

server {
    listen 80;
    server_name dev-admin-kyvc.khuoo.synology.me;

    root /usr/share/nginx/html/frontend_admin;
    index index.html;

    access_log /var/log/nginx/admin-frontend.access.log;
    error_log /var/log/nginx/error.log;
    absolute_redirect off;
    resolver 127.0.0.11 ipv6=off;
    set $backend_admin_api http://kyvc-back-admin-dev:8080;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/admin/auth/ {
        proxy_pass $backend_admin_api/api/admin/auth/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
    }

    location /api/admin/me/ {
        proxy_pass $backend_admin_api/api/admin/me/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
    }

    location /api/admin/backend/ {
        proxy_pass $backend_admin_api/api/admin/backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
    }
}

server {
    listen 80;
    server_name dev-core-admin-kyvc.khuoo.synology.me;

    root /usr/share/nginx/html/frontend_core_admin;
    index index.html;

    access_log /var/log/nginx/core-admin-frontend.access.log;
    error_log /var/log/nginx/error.log;
    absolute_redirect off;
    resolver 127.0.0.11 ipv6=off;
    set $core_admin_api http://kyvc-core-admin-dev:8091;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/admin/core/ {
        proxy_pass $core_admin_api/api/admin/core/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
    }
}
